# Title of Project:-

# Women Cloth Reviews Prediction with Multi Nomial Naïve Bayes


# Objective:-

# Import Library

In [ ]:
import pandas as pd

In [231]:
import numpy as np

In [289]:
import matplotlib.pyplot as plt

# Import Dataset

In [233]:
data=pd.read_csv('https://github.com/YBIFoundation/ProjectHub-MachineLearning/raw/main/Women%20Clothing%20E-Commerce%20Review.csv')

In [234]:
data.head()

Clothing ID  Age                    Title  \
0          767   33                      NaN   
1         1080   34                      NaN   
2         1077   60  Some major design flaws   
3         1049   50         My favorite buy!   
4          847   47         Flattering shirt   

                                              Review  Rating  Recommended  \
0  Absolutely wonderful - silky and sexy and comf...       4            1   
1  Love this dress!  it's sooo pretty.  i happene...       5            1   
2  I had such high hopes for this dress and reall...       3            0   
3  I love, love, love this jumpsuit. it's fun, fl...       5            1   
4  This shirt is very flattering to all due to th...       5            1   

   Positive Feedback        Division Department   Category  
0                  0       Initmates   Intimate  Intimates  
1                  4         General    Dresses    Dresses  
2                  0         General    Dresses    Dresses  
3                  0  General Petite    Bottoms      Pants  
4                  6         General       Tops    Blouses

In [235]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Clothing ID        23486 non-null  int64 
 1   Age                23486 non-null  int64 
 2   Title              19676 non-null  object
 3   Review             22641 non-null  object
 4   Rating             23486 non-null  int64 
 5   Recommended        23486 non-null  int64 
 6   Positive Feedback  23486 non-null  int64 
 7   Division           23472 non-null  object
 8   Department         23472 non-null  object
 9   Category           23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB


In [236]:
data.describe

<bound method NDFrame.describe of        Clothing ID  Age                                              Title  \
0              767   33                                                NaN   
1             1080   34                                                NaN   
2             1077   60                            Some major design flaws   
3             1049   50                                   My favorite buy!   
4              847   47                                   Flattering shirt   
...            ...  ...                                                ...   
23481         1104   34                     Great dress for many occasions   
23482          862   48                         Wish it was made of cotton   
23483         1104   31                              Cute, but see through   
23484         1084   28  Very cute dress, perfect for summer parties an...   
23485         1104   52                    Please make more like this one!   

                             

In [237]:
data.shape

(23486, 10)

In [238]:
data.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                845
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [239]:
data[data['Review']==""]=np.NaN

In [290]:
data['Review'].fillna("No Review",inplace=True)

# Missing Value

In [241]:
data.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                  0
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [291]:
data['Review']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review, Length: 23486, dtype: object

# Define Target(y)and Feature(x)

In [243]:
data.columns

Index(['Clothing ID', 'Age', 'Title', 'Review', 'Rating', 'Recommended',
       'Positive Feedback', 'Division', 'Department', 'Category'],
      dtype='object')

In [244]:
x=data['Review']

In [245]:
y=data['Rating']

In [292]:
data['Rating'].value_counts()

1.0    18208
0.0     5278
Name: Rating, dtype: int64

# Train test split

In [247]:
from sklearn.model_selection import train_test_split

In [248]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,stratify=y,random_state=2529)

In [293]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((16440, 5000), (7046, 5000), (16440,), (7046,))

# Get feature text coversion to tokens

In [250]:
from sklearn.feature_extraction.text import CountVectorizer

In [251]:
cv=CountVectorizer(lowercase=True, analyzer='word', ngram_range=(2,3), stop_words='english', max_features=5000)

In [252]:
x_train=cv.fit_transform(x_train)

In [294]:
cv.get_feature_names_out()

array(['00 petite', '0p fit', '10 12', ..., 'years come', 'yoga pants',
       'zipper little'], dtype=object)

# get model train

In [254]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [255]:
x_test=cv.fit_transform(x_test)

In [256]:
cv.get_feature_names_out()

array(['10 12', '10 dress', '10 fit', ..., 'years come', 'years old',
       'yoga pants'], dtype=object)

In [257]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [258]:
from sklearn.naive_bayes import MultinomialNB

In [259]:
model=MultinomialNB()

In [295]:
model.fit(x_train,y_train)

MultinomialNB()

# Get model predict

In [261]:
y_pred=model.predict(x_test)

In [262]:
y_pred.shape

(7046,)

In [296]:
y_pred

array([1., 1., 1., ..., 1., 1., 1.])

# Get Probability of each predicted classes

In [297]:
model.predict_proba(x_test)

array([[5.43140171e-02, 9.45685983e-01],
       [1.58169512e-01, 8.41830488e-01],
       [7.31367350e-03, 9.92686326e-01],
       ...,
       [3.92486843e-04, 9.99607513e-01],
       [2.24756691e-01, 7.75243309e-01],
       [5.78360255e-02, 9.42163975e-01]])

# Get model Evaluation

In [265]:
from sklearn.metrics import confusion_matrix,classification_report

In [266]:
print(confusion_matrix(y_test,y_pred))

[[  15   13   45   36  144]
 [  43   43   86   85  213]
 [ 116   78  113  166  388]
 [ 166  108  194  336  719]
 [ 371  272  349  722 2225]]


In [267]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

         1.0       0.06      0.02      0.03       711
         2.0       0.09      0.08      0.09       514
         3.0       0.13      0.14      0.14       787
         4.0       0.22      0.25      0.23      1345
         5.0       0.56      0.60      0.58      3689

    accuracy                           0.39      7046
   macro avg       0.21      0.22      0.21      7046
weighted avg       0.37      0.39      0.37      7046



# Recategorise rating as poor(0) and good(1)

In [268]:
data['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

In [269]:
data.replace({'Rating':{1:0,2:0,3:0,4:1,5:1}},inplace=True)

In [270]:
y=data['Rating']

In [271]:
x=data['Review']

# Train Test Split

In [272]:
from sklearn.model_selection import train_test_split

In [273]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,stratify=y,random_state=2529)

In [274]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((16440,), (7046,), (16440,), (7046,))

# Get feature text coversion to tokens

In [275]:
from sklearn.feature_extraction.text import CountVectorizer

In [276]:
cv=CountVectorizer(lowercase=True, analyzer='word', ngram_range=(2,3), stop_words='english', max_features=5000)

In [277]:
x_train=cv.fit_transform(x_train)

In [278]:
x_test=cv.fit_transform(x_test)

# Get Model Re-Train

In [279]:
from sklearn.naive_bayes import MultinomialNB

In [280]:
model=MultinomialNB()

In [281]:
model.fit(x_train,y_train)

MultinomialNB()

In [282]:
y_pred=model.predict(x_test)

In [283]:
y_pred.shape

(7046,)

In [284]:
y_pred

array([1., 1., 1., ..., 1., 1., 1.])

In [285]:
from sklearn.metrics import confusion_matrix,classification_report

In [286]:
print(confusion_matrix(y_test,y_pred))

[[ 449 1134]
 [ 989 4474]]


In [287]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.31      0.28      0.30      1583
         1.0       0.80      0.82      0.81      5463

    accuracy                           0.70      7046
   macro avg       0.56      0.55      0.55      7046
weighted avg       0.69      0.70      0.69      7046

